### ISSUE TITLE
Not responded issue W12-3

### ISSUE THREAD

**Issue by JunWei96** [testathor/pe-results#74] opened 2019-04-03 04:15 UTC
# Description
test
# Team's Response
testing
 ## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment] 2019-04-03 11:50
## Team's Response
test
## State the duplicated issue here, if any
Duplicate of #2

**Comment by testathorStudent** [comment] 2019-04-05 15:49
## Team's Response
test
## State the duplicated issue here, if any
Duplicate of #2

**Comment by testathorStudent** [comment] 2019-04-05 15:52
## Team's Response
testAcceoty
## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment] 2019-04-05 16:58
## Team's Response
yrdy
## State the duplicated issue here, if any
Duplicate of #2

**Comment by testathorStudent** [comment] 2019-04-05 17:13
## Team's Response
test
## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment] 2019-04-17 07:12
## Team's Response
okay
## State the duplicated issue here, if any
Duplicate of #75

**Comment by testathorStudent** [comment] 2019-04-19 06:39
## Team's Response
test
## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment] 2019-04-19 08:51
## Team's Response
test
## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment] 2019-05-15 10:30
## Team's Response
it's ok
asd
33





## State the duplicated issue here, if any
--

**Closed as completed** 2019-09-03 03:38 UTC
Labels: severity.Low, type.DocumentationBug, tutorial.CS2103T-W12, team.3, status.Incomplete
