### ISSUE TITLE
App crashing1

### ISSUE THREAD

**Issue by JunWei96** [testathor/pe-results#1] opened 2019-02-09 14:35 UTC
# Description
- [ ] test
# Team's Response
test
 ## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment] 2019-02-18 05:57
Duplicate of #12
wqe

**Comment by testathorStudent** [comment] 2019-02-26 12:54
## Team's Response
test
## State the duplicated issue here, if any
Duplicate of #71

**Comment by testathorStudent** [comment] 2019-02-26 12:56
## Team's Response
test
## State the duplicated issue here, if any
Duplicate of #

**Comment by testathorStudent** [comment] 2019-02-28 06:13
## Team's Response
aaaa









## State the duplicated issue here, if any
Duplicate of #71

**Closed as completed** 2019-09-03 03:38 UTC
Labels: severity.Low, type.DocumentationBug, tutorial.CS2103T-W12, team.4, status.Done
